### PR TITLE
Remove redundant OCCT headers

### PR DESCRIPTION
**Pull request by Grawp**
Remove the `opencascade/` folder in this repo because:
- It is completely redundant and may not match OCCT specified in `env.yml`. (Keeping correct headers from the OCCT which is actually specified in `env.yml` is completely unnecessary work.)
- Brings hundreds of files from another project into this repo without providing any benefits or reason whatsoever. The local copy does not contain any modifications etc...

The OCCT from which headers should be used is in `env.yml` anyway along with a **specific version number**. There is really no reason to keep the huge copy of those headers here.

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
The headers are used for testing and not included in the package AFAICT. The same goes for the conf file.

**Comment by Grawp** [comment]
For what testing? All your azure jobs are passing correctly in **this PR**.
The headers are there! They ARE INCLUDED IN THE CONDA OCCT PACKAGE FOR ALL THREE ARCHITECTURES IN FULL. Just look at the logs in Azure. They are found and correctly **parsed** by you pywrap **bindgen** thingy!
Everything works.

Could you point me to any test which does not pass? I've just spent two days preparing this and running this in my personal Azure just to be sure I didn't break anything. What have I miss?

And I went directly for a PR without creating an Issue first so you could see proof in the Azure pipelines that it worked first.

**Comment by adam-urbanczyk** [comment]
The files are used in the current pipeline. I'm not saying your PR is not working, it is just testing a different version.

**Comment by Grawp** [comment]
This change mainly modifies the pipeline to use proper headers from **occt conda packages**.
In another words the **main change** is **modification of the pipeline** to use headers directly from occt conda packages.

Removing the `opencascade/` folder is just a finishing touch.

The azure pipeline jobs that ran here in this PR just a few hours ago ran with the new pipeline. It was not the old pipeline from the **master** branch running with just `opencascade/` removed. See e.g. https://dev.azure.com/cadquery/a44cbf0c-deb0-46d5-8ed7-53ba42cd6ec3/_apis/build/builds/1832/logs/34 ..... look  for the occasional clang warnings like
```
2021-10-02T08:18:49.3701177Z   0%|          | 0/313 [00:00<?, ?it/s][W 211002 08:18:49 translation_unit:47] /usr/share/miniconda/envs/cpp-py-bindgen/include/opencascade/Standard_WarningsRestore.hxx
```
to see that it really is using headers from OCCT conda packages.

PS:
If this PR were to be submitted you would get all greens on the **master** branch after the merge and everything would work because again: The core of this change is modification of the pipeline **and not just** removing `opencascade/` folder.

**Comment by Grawp** [comment]
And one of the pipeline changes in this PR is also bumping version of OCCT to the one which is already being successfully by you in the https://github.com/CadQuery/OCP
I'm not bumping it to some arbitrary version.

**Comment by adam-urbanczyk** [comment]
That's the point, I want to keep using the old version here for testing (the newest version shall be built in the OCP repo).

**Comment by Grawp** [comment]
Two questions:
- If it also worked without changing OCCT version, would you consider it?
- Could we do that at least in OCP repo where it certainly does not require bumping OCCT version?

**Comment by adam-urbanczyk** [comment]
Not really, I'm happy with this setup. Sometimes it is needed to manually edit the headers (take a look at the commit history in this repo).

**Pull request closed without merging**
